### ISSUE TITLE
Galar Pokemon

### ISSUE THREAD

**Issue by lyzerglick** [PokeDevs/pokedex-api#6]
New pokemon released in sword and shield are not yet available in the pokedex

**Comment by sks316** [comment]
Any ETA?

**Comment by iamtraction** [comment]
Probably by the end of this weekend.

**Comment by iamtraction** [comment]
Gen 8 pokemon have been added. Some details of the pokemon are missing but will be updated subsequently.

**Comment by sks316** [comment]
There's a small problem when trying to query some Pokemon by name...

```
TypeError: Cannot read property '0' of undefined
    at router.get (/app/src/routes/1/routes/pokemon.js:19:87)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/index.js:281:22
    at param (/rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/index.js:354:14)
    at param (/rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/index.js:410:3)
    at next (/rbd/pnpm-volume/8f1cc2e4-ba74-4740-99a4-de0e2aa815da/node_modules/.registry.npmjs.org/express/4.16.4/node_modules/express/lib/router/index.js:275:10)
```
It's worth noting that the three I tried this with were Meltan, Melmetal, and Snom. It likely happens with others.

**Comment by iamtraction** [comment]
As I mentioned earlier, some fields are empty for the new pokemon. So, look at the returned response and add proper conditions in your application before directly accessing the index of some array as it might not exist.
